version: '3.8'

services:
  usuariosservice:
    build:
      context: ./UsuariosService
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=server=localhost;port=3306;database=usuarios_db;user=root;password=2634
    depends_on:
      - usuarios_db

  productosservice:
    build:
      context: ./ProductosService
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=server=localhost;port=3306;database=productos_db;user=root;password=2634
    depends_on:
      - productos_db

  carritosservice:
    build:
      context: ./CarritoService
    ports:
      - "5003:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=server=localhost;port=3306;database=carritosdb;user=root;password=2634
    depends_on:
      - carritosdb

  pagoservice:
    build:
      context: ./PagoService
    ports:
      - "5004:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=server=localhost;port=3306;database=pagos_db;user=root;password=2634
    depends_on:
      - pagos_db

  pedidosservice:
    build:
      context: ./PedidosService
    ports:
      - "5005:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=server=localhost;port=3306;database=pedidos_db;user=root;password=2634
    depends_on:
      - pedidos_db

  usuarios_db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 2634
      MYSQL_DATABASE: usuarios_db
    ports:
      - "33061:3306"
    volumes:
      - usuarios_data:/var/lib/mysql

  productos_db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 2634
      MYSQL_DATABASE: productos_db
    ports:
      - "33062:3306"
    volumes:
      - productos_data:/var/lib/mysql

  carritosdb:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 2634
      MYSQL_DATABASE: carritosdb
    ports:
      - "33063:3306"
    volumes:
      - carritos_data:/var/lib/mysql

  pagos_db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 2634
      MYSQL_DATABASE: pagos_db
    ports:
      - "33064:3306"
    volumes:
      - pagos_data:/var/lib/mysql

  pedidos_db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 2634
      MYSQL_DATABASE: pedidos_db
    ports:
      - "33065:3306"
    volumes:
      - pedidos_data:/var/lib/mysql

volumes:
  usuarios_data:
  productos_data:
  carritos_data:
  pagos_data:
  pedidos_data: