CREATE DATABASE IF NOT EXISTS pagos_db;
USE pagos_db;

CREATE TABLE IF NOT EXISTS Pagos (
    Id INT NOT NULL AUTO_INCREMENT,
    Metodo VARCHAR(100) NOT NULL,
    Monto DECIMAL(18,2) NOT NULL,
    Fecha DATETIME NOT NULL,
    PRIMARY KEY (Id)
) ENGINE=InnoDB;