CREATE DATABASE IF NOT EXISTS pedidos_db;
USE pedidos_db;

CREATE TABLE IF NOT EXISTS Pedidos (
    Id INT NOT NULL AUTO_INCREMENT,
    PedidoId INT NOT NULL,
    Estado VARCHAR(100) NOT NULL,
    PRIMARY KEY (Id)
) ENGINE=InnoDB;